version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: carservice_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: carservice_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    container_name: carservice_flyway
    depends_on:
      - postgres
    command:
      -url=jdbc:postgresql://postgres:5432/carservice_db
      -user=admin
      -password=admin_pass
      -connectRetries=10
      migrate
    volumes:
      - .:/flyway/sql

volumes:
  postgres_data: